### PR TITLE
OC Bot HomePage Design

### PR DESCRIPTION
**Pull request by 88oo**
Issue: 1

### CODE REVIEW

**Comment by Saishreekouda** [comment]
align buttons horizontally after adding a little more text above it, use svg format of image (without background) and 'what is it all about' is a different section so there should be about 48-56px gap between this section and the hero section. You can add a footer at the end instead of only the logo.

**Comment by 88oo** [comment]
@Saishreekouda pls check if its good now

**Comment by Saishreekouda** [comment]
@Koshal7 the vector will be in the hero section only so for the hero section the vector will be in the right and the text with 3 buttons in the left align the vector to the height of the text, then what is it all about will be another section so the font size of that will be equal to that of OC Python bot and there should be some gap between both the sections. You can ping me on discord for any doubts.

**Comment by 88oo** [comment]
@Saishreekouda is it good now?

**Comment by Saishreekouda** [comment]
yes @Koshal7

**Comment by 88oo** [comment]
can you merge it now @Saishreekouda

**Pull request merged**
